#!/bin/bash

program=${1##*/}
prog=${program%%.*}
suff=${program##*.}

CC="g++ -std=c++11"
SL="g++ -shared"

ROOTLIB="$(root-config --glibs --libs) -lMinuit -lCore -lTMVA"
ROOTINC="$(root-config --cflags)"

INCLUDES="${ROOTINC}"
LIBS="${ROOTLIB}"
CFLAGS="-Wl,--no-as-needed -fPIC"

if [[ "$suff" == "C" || "$suff" == "c" || "$suff" == "cc" ]]
then
    INCLUDES+=`${HOME}/Lynx/Serf-I "${1}"`
    LIBS+=`${HOME}/Lynx/Serf-L "${1}"`
fi


DLLSUF="${DllSuf}"
OBJSUF="${ObjSuf}"
SRCSUF="${SrcSuf}"


echo "${CC} ${program} ${LIBS} ${INCLUDES} ${CFLAGS} -o ${prog}"
