#!/bin/bash


stretch=30 #seconds to stretch
pause=10 #seconds for rest
reps=16 # number of stretches

realstretch=`echo "${stretch}-3" | bc -l`
#realpause=`echo "${pause}-3" | bc -l`

#spaces=`echo "${COLUMNS}/2" | bc -l`


sp="              "
sp1="                  "
sp2="                     "
#sp=""

#for i in `seq 1 1 ${spaces}`
#do
#    sp+=" "
#done

for j in `seq 1 1 ${reps}`
do

    echo -ne "\033[0m"
    echo -ne "\033[H\033[2K${sp}stretch $j of $reps\n\n"
    echo -ne "\033[3;1H\033[2K${sp1}REST !!!\n\n"

    echo -ne "\033[38;5;207m"
    for i in `seq ${pause} -1 4`
    do
	echo -ne "\033[5;1H\033[2K${sp2}$i"
	sleep 1
    done
    for i in `seq 3 -1 1`
    do
	echo -ne "\033[5;1H\033[2K${sp2}$i"
	#echo -ne "\033[5;1H\033[2K${sp2}"`echo "${realpause}+$i" | bc -l`
	aplay /home/dulain/Downloads/button-3.wav 1>/dev/null 2>/dev/null
	sleep 1
    done
    aplay /home/dulain/Downloads/button-35.wav 1>/dev/null 2>/dev/null
    

    
    echo -ne "\033[0m"
    echo -ne "\033[3;1H\033[2K${sp1}BEGIN !!!\n\n"
    echo -ne "\033[38;5;196m"
    
    
    
    for i in `seq 1 1 ${realstretch}`
    do
	echo -ne "\033[5;1H\033[2K${sp2}$i"
	sleep 1
    done
    for i in `seq 1 1 3`
    do
	echo -ne "\033[5;1H\033[2K${sp2}"`echo "${realstretch}+$i" | bc -l`
	aplay /home/dulain/Downloads/button-45.wav 1>/dev/null 2>/dev/null
	sleep 1
    done
    aplay /home/dulain/Downloads/beep-02.wav 1>/dev/null 2>/dev/null    

#    echo -ne "\033[2A\033[2K\b\033[2A\033[2K\b"

done
